### ISSUE TITLE
How LV2_Atom_MIDI is working?

### ISSUE THREAD

**Issue by vallsv** [moddevices/mod-midi-utilities#3]
HI,

I am curious about the way `LV2_Atom_MIDI` is working, cause i reused that that pattern in my code.

I am surprise that there is no specific thing for memory alignment in your code. Cause `lv2_atom_sequence_append_event` can't be aware of the location of `msg`.

 I was expecting something like that:
```
#pragma pack(1)
typedef struct {
    LV2_Atom_Event event;
    uint8_t        msg[3];
} LV2_Atom_MIDI;
```
But it works. Then do you know why and how?

**Comment by falkTX** [comment]
In LV2 atoms, the data follows in memory right after the event.
This struct is just a helper to facilitate reading and writing MIDI events.
Alternatively you could use something like:
```
LV2_Atom_Event* event_ptr = /* stuff for getting event out of atom sequence here */;
uint8_t* midi_bytes = (event_ptr + 1);
midi_bytes[0] = 0x90;
// etc etc for MIDI stuff
```

**Comment by vallsv** [comment]
Yes, but your compiler can pad the address the way it want. Could pad it with 64bit, 32bit...

Or maybe just because it's uint8 data it's fine.

**Comment by falkTX** [comment]
The LV2_Atom_Event is intentionally 64bit aligned (structure wise), so we can easily do things like this.
If you look at other types in https://github.com/drobilla/lv2/blob/master/lv2/atom/atom.h you will see there is no packing macros in use there either, it all just works :)

**Comment by vallsv** [comment]
Yes, i already checked it. That's really weird. Sounds like it works while you compile everything the same way. It's fine for Mod, but for an open environment, it's crazy, that is why there is i guess something i don't know somehow.

Thanks for the answer.
